### ISSUE TITLE
Individual Local Identifier VS animal ID

### ISSUE THREAD

**Issue by bart1** [movebank/data-repository#2]
It seems all datasets use animal-id in the reference data and individual-local-identifier in the observation/event data. This seems inconsistent, not sure if there is a way to fix this, but atleast something to be aware of.

**Comment by sarahcd** [comment]
File downloads from Movebank always use animal-id in the reference data and individual-local-identifier in the data. It's based in the data model so nothing that can be addressed in the published datasets. For this and other name variants for the same information, I clarify in [Movebank's Attribute Dictionary](https://www.movebank.org/node/2381) and the readmes by using "same as", for example

animal ID: An individual identifier for the animal, provided by the data owner. This identifier can be a ring number, a name, the same as the associated tag ID, etc. If the data owner does not provide an Animal ID, an internal Movebank animal identifier may sometimes be shown.
	example: 91876A, Gary
	same as: individual-local-identifier
