### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by bart1** [movebank/data-repository#7]
The links on this page seem to be broken: https://www.datarepository.movebank.org/feed/atom_1.0/10255/3
tested among others the domestic ducks study

**Comment by sarahcd** [comment]
Thanks, I've reported it to the site admin. Do you use the links? If they cannot fix it easily they might just remove the link to this page. But if it's helpful I'll try to find a way to get them working.

**Comment by sarahcd** [comment]
Update: The links are fixed. Let me know if you continue to find any that aren't working.

**Comment by bart1** [comment]
Thanks!
